name = "cf_ai_atlas_memory_chat"
main = "src/worker.ts"
compatibility_date = "2026-01-30"

assets = { directory = "./public", binding = "ASSETS" }

[ai]
binding = "AI"
remote = true

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]
